## Descriptive Statistics

Import NumPy, SciPy, and Pandas

In [1]:
import numpy as np
from scipy import stats
import pandas as pd

Randomly generate 1,000 samples from the normal distribution using ```np.random.normal()```(mean = 100, standard deviation = 15)

In [2]:
samples = np.random.normal(100,15,1000)
samples

array([103.97525755, 124.24617161, 106.1178233 ,  97.60956774,
       117.65149113,  81.09600208,  86.69863052,  95.72849095,
        95.01305346,  81.04125866, 116.85741034,  89.61567273,
        98.71207116, 109.51540641, 116.15664911,  92.85949444,
        86.76279575,  97.30639847, 101.44880394,  88.91961942,
       116.30009406, 123.4743661 ,  78.79330232, 110.31896286,
       113.97065254, 112.60459801,  85.45009415, 103.60417329,
       129.67546377,  93.30613707,  95.95001941, 113.6288859 ,
       106.76850669,  79.351616  ,  86.64882961, 112.62320003,
        94.68542871,  82.17098683,  93.8454212 , 105.9552516 ,
        97.18248392, 115.57089945, 113.67189232, 106.15899269,
       125.86937201, 126.50508992,  74.55677996,  91.6876108 ,
        83.90031121,  71.17778303,  98.5351047 , 121.55212231,
       108.79742533, 106.18275465, 102.3025788 , 113.78805324,
        90.27594511,  80.6726139 ,  86.96346418,  94.78479589,
        87.93198052, 100.95272994, 103.58638537,  98.64037147,
       100.7012037 , 118.18426131, 108.91125621,  80.70319701,
       103.35149318, 109.15504704,  97.86430095,  89.63622169,
        98.55181344,  86.80463121, 100.60085392,  88.74011228,
        75.80007399, 105.29435822, 106.55773984, 106.91299875,
        94.52112503,  88.14285741,  93.88730258,  85.88311858,
       122.00706364,  92.93988465,  84.00156019, 138.60362646,
       117.50207514,  87.11794352, 103.50269317, 118.14107945,
        91.57078859, 111.63559659, 104.63742414, 114.16903906,
       120.53752964, 101.93717683,  84.10799179,  93.0656287 ,
        86.71221588,  80.41998832, 110.98571313,  83.29657834,
       126.55305203,  88.83587911,  93.86411621,  97.19511252,
       128.98165239,  86.83603153, 124.69811771,  87.22247655,
        86.08368166,  96.3232007 ,  95.98166297,  82.04327123,
        94.16680409, 116.37356168,  98.67537151, 108.2078288 ,
       104.62003092, 112.17379295,  94.0680308 , 114.18248967,
        83.14980919, 109.07785252,  63.82380552,  93.76991042,
        85.83885531, 115.0493732 ,  69.6324715 ,  74.57116472,
       129.94593213,  80.86598357, 105.99890708,  88.91089364,
        77.61365053,  89.3475627 , 108.71166917, 120.18899322,
       120.96315669, 118.59245689,  83.49514446,  96.84245032,
       117.89661722,  92.74472024,  80.63543888, 106.79470679,
        78.23099488,  94.42777174,  96.79956035,  70.3140652 ,
        72.84033237, 120.20665648, 103.81337678,  94.35555532,
       123.35459923,  79.63427752,  67.45884506, 104.98886309,
       107.72916633, 116.46099135,  83.91755877, 105.59923889,
       100.55441189,  77.90762597, 102.09131457,  80.40948421,
        72.08328932,  94.16705319,  63.91531557,  97.31303998,
        98.91960871, 118.43555519, 101.71864229,  93.98516007,
       121.95899951, 113.64279954,  93.90357207, 113.36776402,
       101.20008626,  93.50333136, 116.11083077,  96.41649153,
       121.02548731, 111.08380614,  62.22184597, 119.98569171,
       132.88631179,  89.09796647,  83.1282861 ,  65.3700713 ,
        80.57155494, 116.69818188,  90.36347187,  89.72897387,
       129.53034537, 104.61552208, 102.49348298, 119.59652006,
        98.07092573,  96.69812774,  94.73850283,  99.82085977,
       115.47170921,  98.00950812,  81.26266783, 105.65721537,
        83.63431851,  96.21528658, 112.0511626 , 103.37802691,
       125.7185062 , 112.85846853, 115.31523191,  73.3689645 ,
        99.95448067,  96.06284795, 125.60537744,  86.40261608,
        82.84034882,  79.76810423,  88.11708159, 102.59155065,
        79.25413948,  89.27373559, 103.46409624, 100.46018195,
       119.36169174, 107.35522016, 107.90566121,  88.03212858,
       103.39422262, 105.89045049, 111.72494866,  94.35272873,
        89.12574755,  86.05147663, 108.07448639, 103.91546467,
        94.80792166, 112.50138509, 133.73063712, 104.81103114,
       133.01614118,  97.31368528, 123.61258545, 100.58407722,
       118.00808695,  67.75000429,  76.24874847,  85.97451893,
        92.71028445, 144.36338399, 115.78114983, 103.18311132,
       103.82785371,  81.36360496, 111.54103427, 104.48994236,
        90.26602976, 117.65014562,  96.95780287,  95.28043324,
        77.32213245,  95.66304026,  94.42254182,  81.75309801,
       101.11292197,  92.9968163 ,  89.0359774 , 111.5707786 ,
       100.01169499,  97.70759096, 107.19160912, 119.13501905,
        78.82158278, 119.53886355, 112.55839845,  96.6572053 ,
        78.82760122, 133.80560174, 112.98337805,  83.89301076,
       110.21340208, 116.84174241,  98.68165748,  76.62894352,
       115.26891133, 122.96601427, 113.99772761, 104.68677989,
       113.01107921, 109.79902951,  95.73037402,  99.65606888,
        84.17138647,  78.31708564, 111.0773785 , 137.23763224,
        87.26554252, 108.10063447,  71.76877394, 107.36908142,
        95.69625681,  96.45405023,  75.54196414, 124.8388239 ,
       105.73498671,  96.90207522,  98.88549635, 110.58239006,
        87.1429288 , 111.39992107,  91.07084869,  88.06094752,
       112.75047328,  98.05095364,  92.18678768, 138.72429058,
        72.55466262,  76.55202405, 105.11256062, 115.1991526 ,
        84.94949172,  84.70304392,  89.0598281 ,  85.13511887,
       120.39554427,  98.61147977,  81.11916625,  83.23500767,
        80.17167861, 104.91466463,  92.7214861 ,  91.14098805,
       109.90895854, 106.49085429, 108.84335689,  98.78121328,
        99.67178708,  98.91091484, 113.92268059, 103.80718853,
       101.46895648, 122.15682632, 141.53533909, 106.123123  ,
        94.86133897,  68.15440989,  84.77408159, 113.3546281 ,
       136.95398709, 137.79485175, 102.53448238, 110.2971568 ,
       130.05929302,  79.90298005,  81.54784911, 113.45446198,
        91.51970211,  93.906049  ,  83.68517034, 116.28589514,
        76.37952135, 143.91465403, 117.74079429, 124.98883724,
        88.4898791 ,  89.18804054, 120.44856488, 106.85252654,
        73.14048812,  74.16191662,  69.14445345, 118.12912338,
        92.82657924,  98.43434359, 124.70474644, 102.32946882,
       105.64336504,  88.13833056,  69.28174637,  91.93265601,
       113.55883359,  89.97776297, 107.63938222, 114.75135732,
        91.28012728, 102.32640277,  89.97201664, 109.93542673,
       118.35159301,  88.0542088 ,  90.16523926,  90.94574886,
        92.56391816, 114.95327466,  91.32802507,  57.38807292,
        99.68109857,  93.2110817 , 120.39713625,  99.54507343,
       108.28024   , 126.02280818,  99.43633668, 101.75182329,
       132.35381319,  92.05364767, 108.32102528,  95.82401646,
        99.02834954,  80.30911551,  75.87827641, 116.84629207,
        73.63389293, 122.07689354, 107.39580323,  65.85663872,
        94.62212148,  82.79459881, 124.3470293 ,  93.62408418,
        97.30990002, 103.77176658,  95.56153999,  84.09948765,
       113.57571723,  77.51024496,  85.94022047,  86.50553906,
        93.8120106 , 113.57944748,  83.20686034, 124.18040073,
       110.91941985,  93.80420222, 120.89773511, 100.63303124,
        93.92125904, 107.34901381, 112.27505192,  81.33366125,
        67.87559984,  94.20515425,  77.42192958,  78.07101538,
       104.2398328 , 110.67704186, 117.39620544,  74.41173717,
       102.8050463 , 125.86323278, 103.11365243, 158.4836793 ,
        89.6550309 , 102.35777725, 108.6063227 , 104.56416795,
        79.09849955,  69.93111753, 105.18720252, 101.91414618,
       123.80520008,  98.99631267, 109.33800882,  90.07235372,
       103.1276392 ,  94.46851114,  90.83439194, 122.17340964,
       128.88333398, 115.9790616 , 109.31797157, 128.33017243,
       104.28013955,  73.53121068,  80.87941026,  92.77888857,
        95.70273259,  71.04162678, 112.64499706,  93.63448619,
       103.55994906,  89.86916178, 107.32207888,  95.92373122,
        82.5180223 , 112.47715273,  99.0266351 ,  86.20807737,
        77.82670839,  93.2082367 ,  89.39254981,  74.29398351,
       120.92249118,  99.63653967, 111.7414735 ,  88.31289625,
        88.18491962, 111.06045434, 101.72765432,  89.79217939,
        99.39344256, 105.68294121, 111.05215618,  95.15088122,
       110.87073432, 122.96703781, 101.33038813, 110.99288496,
       100.789895  , 103.29049159,  95.73273842, 113.63440285,
        94.3547043 ,  88.98642085, 125.02651444, 102.07604277,
       101.21781937,  99.36896419, 114.33362966,  99.97272065,
        79.01042624, 102.08256471, 118.54050972,  97.83860077,
        75.56911162, 117.79730105,  91.63956146,  97.64626482,
       114.27522651, 102.89426869,  71.69363796,  92.62880773,
        97.44213948,  98.11639413, 106.52788708,  70.15050358,
        95.90765373,  95.19965884, 136.23626017, 103.86461018,
        97.70083499, 112.36444171,  94.37889367, 126.36248841,
       110.88855797, 102.60934453,  82.36246942, 104.00576052,
        99.04897351, 110.78891915, 107.78603427,  77.68904667,
       110.10569889,  85.77746639,  91.16824294, 100.52801041,
       113.39578069, 118.45908654, 101.14422753, 115.57606993,
        82.17524347,  95.29164168, 133.62739132,  91.48072895,
       121.61130844, 102.79873442,  88.97050872, 105.45724525,
       107.48049862, 100.20216968, 120.81157829, 118.27272725,
       101.23808017, 108.36790836, 106.80295547,  84.65360078,
       115.57632287,  99.32661288,  91.45351941,  99.27178452,
        97.3848018 , 109.14419205,  89.08202623, 117.5657296 ,
       115.65549424,  71.88218294, 115.49185071,  96.96157773,
       125.19172464,  97.71026565,  88.14494418, 120.96835437,
        83.25144525, 112.18512008,  81.95151832, 110.03981622,
       112.76477613,  91.87750714, 102.19430703, 104.57084507,
        88.4405162 ,  96.20835473, 120.2299742 , 112.49378417,
        90.11223675, 114.77407776, 102.93801071, 123.56254851,
        86.25623575,  96.26560206, 125.9971828 , 131.3524533 ,
       109.79105217,  70.52436479,  99.82127601, 109.78101183,
        92.79998582,  79.59103025,  95.27031449,  97.04077058,
       110.85055674, 101.85186901, 117.66325368, 125.19777746,
       107.96358327,  80.04623068,  91.0780888 ,  99.58393349,
        95.31307861, 132.53142292, 112.97524821,  90.47833909,
       117.85860089, 110.8201958 , 100.90381888,  95.02467679,
       123.48453905, 110.85820028, 107.35466164,  77.14145126,
        95.07063106, 108.58697197,  86.90780271,  86.15671374,
        84.39533788,  84.17616905, 106.75000343,  76.61107448,
        97.19436808,  91.14979379,  78.13817737, 103.08353333,
        75.20552175, 101.91301001,  88.86011825,  85.3509989 ,
        99.10809726, 110.67341904,  90.64108772,  96.29245249,
       102.13891498, 109.36155534,  87.77506558, 115.37213848,
        79.05715913, 112.92585498, 116.03087345, 127.00945702,
       107.68755941, 104.92788604, 113.90496315,  84.62704665,
        96.40430818,  65.7832128 ,  99.15858162,  85.64586674,
        79.11762927, 106.19284634,  85.10151925, 109.72217067,
        90.4258419 ,  93.55308794,  90.9868548 ,  98.5333932 ,
        78.98194967,  88.80300042,  90.34601921, 108.55017054,
        85.73692934,  77.46845642,  92.04151301, 120.50348956,
        90.37904379,  99.18751141, 101.16453062, 110.65578521,
       103.44707291, 103.62323853,  94.19566257, 113.53892873,
       105.50009799,  70.17873391,  99.9789758 ,  80.172164  ,
        77.69951319, 110.4860708 ,  97.08832214, 100.11205809,
        98.03413514, 103.44537126, 132.12687119,  97.76200798,
       107.73368434,  87.71428405, 104.42825685, 100.91500427,
        78.28635959, 108.53059191,  81.60865436, 106.41598129,
        95.94806588, 100.48687954,  84.2204603 ,  88.48599028,
       101.33614706, 105.30063126, 122.8471384 , 104.29920413,
       100.49223256,  72.7848266 , 100.68336635,  93.94149414,
       108.08550306,  91.20086868,  77.58982554, 122.33309389,
       115.04884799, 104.176768  , 103.83742367, 106.24087789,
       103.32472611, 120.41270636, 122.1014415 , 106.02854024,
       111.52709727, 113.68572286,  88.47742749, 108.36523439,
       107.90586126,  99.20911805, 103.14149721,  69.69525026,
       103.36160319,  79.56168595, 100.55949381, 117.58635529,
       103.24030586, 117.85262787,  87.08666689,  99.52846789,
        80.1217025 ,  86.84885439, 110.90761376, 110.39665719,
       104.56844361,  94.1030746 ,  77.60320481,  84.63849315,
        78.75062462,  87.83066714,  91.9934843 , 117.84464068,
       116.24150896, 130.40680487, 109.86898448,  94.85889966,
        96.48568613,  90.68869928, 100.99216077,  84.29511577,
       108.39960517,  83.55348418,  81.46369038,  84.37007967,
        80.47705073,  98.39101321, 107.00393037, 124.07973133,
       101.94053251, 100.38757575,  89.52158857, 109.02910734,
       109.45441381, 120.49181445,  91.93065424, 110.05239868,
        99.35918834, 126.28896363, 119.58133416, 116.06453226,
       127.15745451,  88.64272941,  87.98481643, 103.9343454 ,
       117.23214228, 112.75357429,  72.85304389, 102.84781011,
        98.35450863,  73.60429382,  96.34084275,  72.36472748,
        91.10942114, 110.28428027, 104.09013931, 111.90439237,
        86.29704677, 119.71940964, 115.02967152,  83.86867664,
       106.87299573,  89.34695717,  92.71047757,  86.85246207,
        81.1269596 ,  99.41315458, 104.23644621,  91.23839879,
        98.6238217 ,  90.18313635,  94.87907381,  83.90581149,
        92.62683499, 128.91645921, 103.78549023,  84.48261339,
       120.82562382, 107.39120541, 112.41177015, 126.16249717,
       101.1253871 ,  93.43132983, 108.17502637, 126.11915492,
       110.98668696,  98.35714358,  90.76045041, 126.16187233,
       104.19809667,  84.45335804,  70.50986036, 102.62302368,
        98.09215896, 116.30263042, 111.50563982,  86.5792095 ,
        83.56816267,  86.29999232, 103.521253  , 112.41978022,
       101.42049782,  83.22464945,  97.77744261, 109.61072312,
        87.49254244, 118.29124561,  94.2071902 , 111.21078617,
        81.14372638,  94.66631091,  84.03753742, 101.24994868,
        93.8623067 ,  81.1709238 , 103.11915494, 104.19763961,
        90.62015149, 115.73869443,  82.63775629,  77.53818609,
        96.43210451, 123.36200782,  92.84682728,  95.146914  ,
        91.81726682, 102.80353443, 117.90587227, 109.49520679,
        92.38383238, 104.58706983, 104.3749695 ,  94.35552371,
        94.69162691, 107.56801397,  70.04493055,  87.49124055,
        92.94487505, 107.7323426 ,  96.83637084, 118.66111596,
        78.08084835, 110.05010298,  99.87733724, 103.55376472,
       121.28560861,  94.4247254 ,  94.86457373,  88.30172399,
       107.96979696,  95.7418535 ,  77.27151035, 103.93836326,
       102.94464055,  82.42609313, 112.52585991, 103.65809818,
       101.6375511 , 113.93139082,  96.58363382,  96.76511255,
       113.90007006, 111.42484599,  73.81113661, 102.2469916 ,
        85.72630889, 120.23740013, 113.00893923, 108.67607471,
        89.89958621, 100.63655006,  77.25374494,  95.85054933,
       120.76802621, 104.23926972, 119.15395097,  95.3640186 ,
       120.38049501,  95.02334984,  83.22999083,  92.61640537,
       107.33202646, 126.76057236,  69.81959185,  70.23267728,
       128.71556191,  94.55585136, 101.04039395,  93.50228872,
       106.72698527, 107.28042068, 117.18206023, 115.33561466,
       111.83119493,  97.88191115,  78.05103387,  91.40079127,
       113.77079681,  85.58258952, 122.57033846,  95.32079231,
        74.13160584, 122.46080672, 133.11087819,  91.04927507,
        88.88801393,  86.49641047, 134.97644405,  88.17956261,
        92.72262317,  63.55272798, 114.77998457, 102.16509276,
        77.36696873, 103.85151136, 122.44141809,  86.43438775,
        87.31071383, 100.99519416,  93.51985199,  94.95113973,
       105.13010421,  90.30584987, 109.0308235 , 111.91368707,
       111.88063909,  96.02513397,  96.35375184, 126.02688365,
       115.46909081, 122.53769794, 106.82000069,  95.15229034,
        88.82214538, 105.70804035, 110.36270333,  90.33882705])

Compute the mean, median, and mode

In [3]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)
print("mean :" , mean)
print("median :", median)
print("mode :", mode)

mean : 100.06291523698387
median : 99.75097917068027
mode : ModeResult(mode=array([57.38807292]), count=array([1]))

Compute the min, max, Q1, Q3, and interquartile range

In [4]:
min = samples.min() 
max = samples.max()
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = stats.iqr(samples)
print("min :", min)
print("max :", max)
print("q1 :", q1)
print("q3 :", q3)
print("iqr :", iqr)

min : 57.38807292043404
max : 158.48367930031378
q1 : 89.2523118286846
q3 : 110.85246762444105
iqr : 21.60015579575645

Compute the variance and standard deviation

In [5]:
variance = np.var(samples)
std_dev = np.std(samples)
print("variance :", variance)
print("standard deviaton :", std_dev)

variance : 230.67594159332535
standard deviaton : 15.188019673193914

Compute the skewness and kurtosis

In [6]:
from scipy.stats import skew,kurtosis


print("skewness :",(stats.skew(samples)))

print("kurtosis :",(stats.kurtosis(samples)))

skewness : 0.10891819091198572
kurtosis : -0.19516609901657178

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use np.arange()

In [7]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use np.array() to create a second array y containing 10 arbitrary integers.

In [8]:
y = np.array(np.random.randint(50, size=10))
y

array([49, 24, 14, 14, 11, 10, 33, 47, 28, 34])

Once you have two arrays of the same length, you can compute the correlation coefficient between x and y

In [9]:
r = np.corrcoef(x, y)
r

array([[1.        , 0.14557215],
       [0.14557215, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [10]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method to calculate Pearson's r correlation.

In [11]:
r = stats.pearsonr(x,y)
r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [12]:
rho = stats.spearmanr(x,y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [13]:
import seaborn as sns

In [14]:
tips = sns.load_dataset("tips")
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [15]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [16]:
stats.pearsonr(tips["total_bill"],tips["tip"])

(0.6757341092113642, 6.6924706468640476e-34)